print("###############################################") 
print("----------------Manipulasi String--------------") 
print("---------------Created: Dzaya 2022-------------") 
print("\n########## Menggabungkan String ###########\n") 
#menggabungkan String (Concate) 
F_name=input('Masukan Nama Depan :') 
M_name=input('Masukan Nama Tengah :') 
L_name=input('Masukan Nama Belakang :') 
spasi=(' ') 
full_name=F_name+spasi+M_name+spasi+L_name 
print('nama lengkap anda =',full_name) 
print("\n########## Melihat Panjang String #########\n") 
panjang=len(full_name) 
kar=F_name+M_name+L_name 
J_kar=len(kar) 
print('panjang string didalam nama lengkap anda =',panjang) 
print('jumlah huruf didalam nama lengkap anda =',J_kar) 
a=input('\nmasukan huruf yang ingin diketahui jumlahnya =') 
jml=full_name.count(a) 
print('jumlah huruf ',a,' didalam nama lengkap anda =',jml) 
print("\n################# Indexing ################\n") 
print('Urutan ke 0 =', full_name[0]) 
print('Urutan ke 1 =', full_name[1]) 
print('Urutan ke 2 =', full_name[2]) 
print('Urutan ke 3 =', full_name[3]) 
print('Urutan ke 4 =', full_name[4]) 
print('Urutan ke 5 =', full_name[5]) 
print('Urutan ke 6 =', full_name[6]) 
print('Urutan ke 7 =', full_name[7]) 
urut=input('\nmasukan no .urutan huruf yang ingin diketahui =') 
x=int(urut) 
y=full_name[x] 
print('Urutan ke ',urut +' adalah karakter: '+ y) 
print("\n################# Mengubah Bentuk ################\n") 
ascii_code=ord(y) 
print('bentuk ascii dari karakter',y,' adalah: ',ascii_code) 
z=chr(ascii_code) 
print('bentuk karakter dari ascii code',ascii_code,' adalah: ',z)