#fungsi untuk alokasi karakter
#ljust()=leftjustify
#rjust()=rightjustify
#center()
#strip()=menghilang format alokasi
rtkanan="contoh rata kanan".rjust(50,'*')
rtkiri="contoh rata kiri".ljust(50,"=")
rttengah="manipulasi string".center(50,";")
rttengah1="Created: Dzaya 2022".center(50,':')
print(""+rtkanan+"")
print(""+rttengah+"")
print(""+rttengah1+"")
print(""+rtkiri+"")
rtkiri1="contoh strip".strip("=")
print(""+rtkiri1+"")
a=input('masukkan nama :')
print('nama :',a)
b=a.isalpha()
c=a.islower()
d=a.isupper()
e=a.isspace()
f=a.istitle()
print('apakah nama dalam bentuk alfabet ?:',b)
print('apakah nama dalam bentuk huruf kecil ?:',c)
print('apakah nama dalam bentuk huruf kapital ?:',d)
print('apakah dalam nama terdapat spasi ?:',e)
print('apakah awal kata terdapat huruf kapital ?:',f)
print("\n################### mengubah string ###############\n")
print('nama:',a)
a1=a.upper()
print('mengubah nama menjadi huruf kapital :',a1)
a2=a.lower()
print('mengubah nama menjadi huruf kecil :',a2)