print("##########################################################")
print("---------Manipulasi String----------------")
print("---------Created: Dzaya 2022------------------")
print("\n######### Menggabungkan String ####################\n")

#menggabungkan string (concate)
F_name=input('Masukkan Nama depan :')
M_name=input('Masukkan Nama Tengah :')
L_name=input('Masukkan Nama Belakang :')
spasi=('')
full_name=F_name+spasi+M_name+spasi+L_name
print('nama lengkap anda =', full_name)
print("\n######## Melihat Panjang string ###########")
panjang=len(full_name)
kar=F_name+M_name+L_name
J_kar=len(kar)
print('panjang string di nama lengkap anda =',panjang)
print('jumlah hurup di nama lengkap anda =',J_kar)
a=input('\n masukkan huruf yang ingin di ketahui jumlahnya =')
jml=full_name.count(a)
print('jumlah huruf ',a,' didalam nama lengkap anda =',jml)
print("\n##################### indexing #####################\n")
print('Urutan ke 0 =',  full_name[0])
print('Urutan Ke 1 =', full_name[1])
print('Urutan Ke 2 =', full_name[2])
print('Urutan Ke 3 =', full_name[3])
print('Urutan Ke 4 =', full_name[4])
print('Urutan Ke 5 =', full_name[5])
print('Urutan Ke 6 =', full_name[6])
print('Urutan Ke 7 =', full_name[7])
urut=input('\nmasukkan no .urutan huruf yang ingin di ketahui =')
x=int(urut)
y=full_name[x]
print('Urutan ke', urut +'adalah karakter:'+ y)
print("\n###################### Mengubah Bentuk ######################\n")
ascii_code=ord(y)
print('bentuk ascii dari karakter',y,'adalah:', ascii_code)
z=chr(ascii_code)
print('bentuk  karakter dari ascii code',ascii_code,'adalah:',z)